import React from 'react';
import { useAppStore } from '@/store/useAppStore';
import InstructionCard from '@/components/common/InstructionCard';

const MainDomainInstructionCard = () => {
    const { settings } = useAppStore();
    return (
        <div className={settings?.domain?.main_domain ? 'mt-4 flex flex-col gap-4 h-[55vh] pb-4 overflow-y-scroll' : 'hidden'}>
            <h3 className="text-[14px] font-[700] text-[#333]">Instructions</h3>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                You need to make sure that the following records are added to your domain's DNS
                records
            </p>
            <InstructionCard
                title="Main Domain"
                recordType="CNAME"
                name="www"
                value="cname.vercel-dns.com"
                ttl="14400"
            />
            <InstructionCard
                title="Main Domain"
                recordType="A"
                name="@"
                value="216.198.79.1"
                ttl="14400"
            />
            <h1 className="text-[14px] font-[700] text-[#333]">Note</h1>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                1. It may take up to 24 hours for DNS propagation.
            </p>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                2. SSL is generated by Hyperblog after verifying the DNS propagation.
            </p>
        </div>
    );
};

export default MainDomainInstructionCard;
