import { useAppStore } from '@/store/useAppStore';
import React from 'react';
import InstructionCard from '@/components/common/InstructionCard';

const SubDomainInstruction = () => {
    const { settings } = useAppStore();
    return (
        <div className={settings?.domain?.sub_domain ? 'mt-4 flex flex-col gap-4' : 'hidden'}>
            <h3 className="text-[14px] font-[700] text-[#333]">Instructions</h3>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                You need to make sure that the following records are added to your domain's DNS
                records
            </p>
            <InstructionCard
                title="Sub Domain"
                recordType="CNAME"
                name={settings?.domain?.sub_domain?.split('.')[0] || ''}
                value="7edd924ce36319ac.vercel-dns-017.com"
                ttl="14400"
            />

            <h1 className="text-[14px] font-[700] text-[#333]">Note</h1>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                1. It may take up to 24 hours for DNS propagation.
            </p>
            <p className="text-[14px] font-[500] text-[#8F8F8F]">
                2. SSL is generated by Hyperblog after verifying the DNS propagation.
            </p>
        </div>
    );
};

export default SubDomainInstruction;
