import React from 'react';
import CenteredModal from '@/components/common/Modals/CenteredModal';
import Button from '@/components/common/Buttons';

interface ConnectConfirmationModalProps {
    isOpen: boolean;
    onClose: () => void;
    onConnect?: () => void;
    domain?: string;
}

const ConnectConfirmationModal: React.FC<ConnectConfirmationModalProps> = ({
    isOpen,
    onClose,
    onConnect,
    domain = 'colorlet.com',
}) => {
    const footerComponent = (
        <div className="flex items-center w-full gap-2">
            <Button type="default" onClick={onClose} className="rounded-xl h-[32px] w-full">
                Cancel
            </Button>
            <Button
                type="primary"
                onClick={onConnect}
                className="rounded-xl h-[32px] w-full !bg-[#28A745] hover:!bg-[#2fc751]"
            >
                Connect
            </Button>
        </div>
    );

    return (
        <CenteredModal
            isOpen={isOpen}
            onClose={onClose}
            title="Wait a Minute"
            footerComponent={footerComponent}
            width={480}
            hideDivider={true}
            contentClassName="!py-4 "
            childrenClassName="!py-4 "
        >
            <div className="space-y-6">
                <div className="space-y-2 border-b border-[#E0E0E0] pb-4">
                    <p className="text-[#8F8F8F] text-[14px] font-[500]">
                        We noticed that you are connecting your main domain{' '}
                        <span className="font-bold text-[#333]">{domain}</span>
                    </p>
                    <p className="text-[#8F8F8F] text-[14px] font-[500] mt-4">
                        Are you sure that you want to use Hyperblog for your entire site?
                    </p>
                </div>

                <div>
                    <h3 className="text-[16px] font-[500] mb-2">Note</h3>
                    <ol className="list-decimal list-inside space-y-2">
                        <li className="text-[#8F8F8F] text-[14px] font-[500]">
                            It may take up to 24 hours for DNS propagation.
                        </li>
                        <li className="text-[#8F8F8F] text-[14px] font-[500]">
                            SSL is generated by Hyperblog after verifying the DNS propagation.
                        </li>
                    </ol>
                </div>
            </div>
        </CenteredModal>
    );
};

export default ConnectConfirmationModal;
