import googleFonts from '@/constants/common/google-fonts.json';

export const SeoSettingForm = [
    {
        name: 'meta_title',
        label: 'Meta Title',
        inputType: 'text',
        placeholder: 'Enter meta title',
        description: "This is the meta title of your Hyperblog's homepage.",
        required: true,
    },
    {
        name: 'meta_description',
        label: 'Meta Description',
        inputType: 'textarea',
        placeholder: 'Enter meta description',
        description: "This is the meta description of your Hyperblog's homepage.",
        required: true,
    },
    {
        name: 'google_analytics_id',
        label: 'Google Analytics Id',
        inputType: 'text',
        pattern: /^UA-\d{4,10}-\d{1,4}$|^G-[A-Z0-9]{5,}$/i,
        placeholder: 'UA-XXXXXX or G-XXXXX',
        description:
            'If entered, a cookie-popup is displayed to visitors to comply with EU-Law(GDPR)',
    },
    {
        name: 'google_adsense_publisher_id',
        label: 'Google Adsense Publisher Id',
        inputType: 'text',
        pattern: /^ca-pub-\d{10,20}$/,
        placeholder: 'ca-pb-XXXXXXXXX',
        description: 'It only works with Auto ads. You cannot use custom ad units.',
    },
    {
        name: 'google_adsense_ads_txt',
        label: 'Google Adsense Ads.txt',
        inputType: 'textarea',
        placeholder: 'ca-pb-XXXXXXXXX',
        description: 'Paste your ads.txt contents here',
        hasToggle: true,
        toggleLabel: 'Do not show the default cookie-popup notice',
        toggleDescription:
            'You can use your own cookie-popup notice by copy pasting custom javascript code below.',
    },
    {
        name: 'default_cookie_popup',
        inputType: 'switch',
        label: 'Enable Default Cookie Popup',
        sublabel: 'Show the default cookie popup if enabled.',
    },
    {
        name: 'privacy_policy_url',
        inputType: 'text',
        label: 'Privacy Policy URL',
        placeholder: 'https://example.com/privacy-policy',
        description: 'This URL will be added to the cookie-popup.',
    },
    {
        name: 'hide_authors',
        inputType: 'switch',
        label: 'Hide Authors',
        sublabel: "You can hide author's name for all posts on your blog.",
    },
    {
        name: 'hide_post_dates',
        inputType: 'switch',
        label: 'Hide Post Dates',
        sublabel: 'You can hide dates for all posts on your blog.',
    },
    {
        name: 'hide_social_sharing_icons',
        inputType: 'switch',
        label: 'Hide Social-sharing Icons',
        sublabel: 'This is a site-wide setting. You can control on individual posts also.',
    },
    {
        name: 'hide_default_menu_items_in_footer',
        inputType: 'switch',
        label: 'Hide Default Menu Items in Footer',
        sublabel: 'You can hide the menu items like Search, Tags etc that are shown in the footer.',
    },
    {
        name: 'show_searchbar_on_homepage',
        inputType: 'switch',
        label: 'Show Searchbar on Homepage',
        sublabel: 'Show or hide the searchbar on your homepage.',
    },
    {
        name: 'send_email_upon_deploy',
        inputType: 'switch',
        label: 'Send Email upon Deploy',
        sublabel: 'Receive an email notification when your Hyperblog is deployed.',
    },
    {
        name: 'show_post_progress_bar_on_scroll',
        inputType: 'switch',
        label: 'Show Post Progress Bar on Scroll',
        sublabel: 'Displays a progress bar at the top of post pages based on scroll position.',
    },
    // {
    //     name: 'homepage_type',
    //     inputType: 'switch',
    //     options: ['static_page', 'recent_posts'],
    //     label: 'Homepage',
    //     sublabel: 'Displays recent post or static page in home page.',
    // },
    {
        name: 'miscellaneous_scripts',
        label: 'Miscellaneous Scripts',
        inputType: 'textarea',
        placeholder: '<script>...</script>',
        description: 'Paste any additional scripts you want to include site-wide.',
    },
    {
        name: 'head_scripts',
        label: 'Head Scripts',
        inputType: 'textarea',
        placeholder: '<script>...</script>',
        description: 'Scripts inserted inside the <head> tag of your site.',
    },
    {
        name: 'custom_css',
        label: 'Custom CSS',
        inputType: 'textarea',
        placeholder: 'body { background: #000; }',
        description: 'Add your custom CSS styles here.',
    },
    {
        name: 'custom_robots_txt',
        label: 'Custom robots.txt',
        inputType: 'textarea',
        placeholder: 'User-agent: *\nDisallow:',
        description: 'Specify custom rules for web crawlers.',
    },
];

export const AdvancedSettingForm = [
    // {
    //     name: 'short_description',
    //     label: 'Short Description',
    //     inputType: 'textarea',
    //     placeholder:
    //         'You can add a great description here to make the blog readers visit your landing page.',
    //     description: '65 characters max',
    // },
    {
        name: 'logo',
        label: 'Logo',
        inputType: 'image',
        imageDimension: '360 X 120',
        required: true,
        isCroppable: true,
    },
    {
        name: 'color_palette',
        label: 'Color Palette',
        inputType: 'color_palette',
        placeholder: 'e.g. #ffffff, #000000',
        required: true,
    },
    {
        name: 'fav_icon',
        label: 'Favicon',
        inputType: 'image',
        imageDimension: '32 X 32',
        required: true,
    },
    {
        name: 'blog_ui_font',
        label: 'Blog UI Font',
        placeholder: 'e.g. Inter, Roboto',
        inputType: 'select',
        options: googleFonts,
        fontsPreview: true,
        required: true,
    },
    {
        name: 'blog_post_font',
        label: 'Blog Post Font',
        placeholder: 'e.g. Georgia, Open Sans',
        inputType: 'select',
        options: googleFonts,
        fontsPreview: true,
        required: true,
    },
    {
        name: 'header_title',
        label: 'Header Title',
        inputType: 'text',
        placeholder: 'Enter blog header title',
        samplePreview: true,
        required: true,
        mode: 'title',
    },
    {
        name: 'header_caption',
        label: 'Header Caption (optional)',
        inputType: 'text',
        placeholder: 'Enter blog header caption',
        samplePreview: true,
        mode: 'caption',
    },
    {
        name: 'header_cta_button',
        label: 'Header CTA Button Text & Link (optional)',
        inputType: 'cta_input',
        samplePreview: true,
        mode: 'cta',
    },
    {
        name: 'categories_filter',
        label: 'Categories Filter',
        inputType: 'select',
        variant: 'multi',
        placeholder: 'Add category filters',
        required: false,
        samplePreview: true,
        mode: 'categories',
    },
    {
        name: 'fixed_navbar',
        label: 'Fixed Navigation Menu',
        sublabel: 'if enabled, the navigation menu will be fixed in the top always.',
        inputType: 'switch',
    },
    {
        name: 'graph_image',
        label: 'Open Graph Image (Social-sharing Preview)',
        inputType: 'image',
        imageDimension: '1200 X 630',
        required: true,
    },
    {
        name: 'footer_logo',
        label: 'Footer Logo',
        inputType: 'image',
        imageDimension: '360 X 120',
        required: true,
        isCroppable: true,
    },
];

export const AuthorSettingForm = [
    {
        title: 'Basic Details',
        fields: [
            {
                name: 'author_name',
                label: 'Name',
                inputType: 'text',
                placeholder: 'Enter author name',
                className: 'col-span-1',
            },
            {
                name: 'author_designation',
                label: 'Designation',
                inputType: 'text',
                placeholder: 'Enter author designation',
                className: 'col-span-1',
            },
            {
                name: 'author_bio',
                label: 'Short Bio',
                inputType: 'textarea',
                placeholder: 'Enter author short bio',
                description: '65 characters max',
                className: 'col-span-2',
            },
            {
                name: 'author_image',
                label: 'Upload Author Image',
                inputType: 'image',
                imageDimension: '360 X 120',
                className: 'col-span-2',
            },
        ],
    },
    {
        title: 'Social Links',
        fields: [
            {
                name: 'facebook',
                label: 'Facebook',
                inputType: 'text',
                placeholder: 'Enter author facebook link',
                className: 'col-span-1',
            },
            {
                name: 'x',
                label: 'X',
                inputType: 'text',
                placeholder: 'Enter author x link',
                className: 'col-span-1',
            },
            {
                name: 'website',
                label: 'Website',
                inputType: 'text',
                placeholder: 'Enter author website link',
                className: 'col-span-1',
            },
            {
                name: 'linkedin',
                label: 'LinkedIn',
                inputType: 'text',
                placeholder: 'Enter author linkedin link',
                className: 'col-span-1',
            },
        ],
    },
];
