'use client';

import React, { useEffect, useCallback, useRef, useState } from 'react';
import { useOnboardingStore, OnboardingBlockStep } from '@/store/useOnboardingStore';
import OnboardingSpotlight from './OnboardingSpotlight';
import OnboardingTooltip from './OnboardingTooltip';
import { waitForElement, scrollToElement, dataTourSelector } from '@/utils/onboarding.utils';
import { useAppStore } from '@/store/useAppStore';
import { sampleBlogData } from '@/data/sampleBlogData';
import aiSuggestionsApi from '@/api/ai-suggestions.api';
import { apiUpdateProductTour } from '@/api/auth';
import bannersApi from '@/api/banner.api';
import blogApi from '@/api/blog.api';
import { handleConvertBannerComponentToImage } from '@/components/editor/Banner/helper';

// ─── Block types we highlight during walkthrough ─────────────────────────────
const BLOCK_SEQUENCE: { type: string; dataTour: string; label: string }[] = [
    { type: 'banner',       dataTour: 'banner-block',      label: 'Banner Block' },
    { type: 'infograph',    dataTour: 'infograph-block',   label: 'Infographic Block' },
    { type: 'poll',         dataTour: 'poll-block',        label: 'Poll Block' },
    { type: 'faq',          dataTour: 'faq-block',         label: 'FAQ Block' },
    { type: 'lead_magnet',  dataTour: 'lead-magnet-block', label: 'Lead Magnet Block' },
    { type: 'youtube_video',dataTour: 'youtube-block',     label: 'YouTube Video Block' },
];

const BLOCK_DESCRIPTIONS: Record<string, string> = {
    banner:       'An AI-generated banner to grab your readers\' attention instantly.',
    infograph:    'A visually rich infographic automatically created for your topic.',
    poll:         'Engage your audience with this AI-generated poll question.',
    faq:          'Frequently Asked Questions generated by AI for your content.',
    lead_magnet:  'A lead magnet block with auto generated lead resource to capture reader emails and grow your audience.',
    youtube_video:'A relevant YouTube video automatically discovered for your topic.',
};

/**
 * Editor Onboarding Layer (Steps 2–7).
 * 
 * Key behaviours:
 * - "Load Demo Content" inserts the FULL enhanced data (including AI blocks) directly.
 *   This skips the real Enhance API call entirely.
 * - No skip/close button after step 1 (dashboard).
 * - Accepts/rejects from each block auto-advance to the next block via
 *   the `onboarding:block-action` custom event.
 * - Spotlight padding is large enough to include the Accept/Reject bar.
 */
export default function EditorOnboarding() {
    const {
        isActive,
        phase,
        setPhase,
        completeOnboarding,
        blockSteps,
        setBlockSteps,
        currentBlockIndex,
        advanceBlockStep,
        currentBlogId,
        demoContent,
    } = useOnboardingStore();

    const { blog, setBlog, handleBlogFieldChange } = useAppStore();
    const [isInsertingContent, setIsInsertingContent] = useState(false);
    const setupRef = useRef<Record<string, boolean>>({});

    const isEditorPhase = isActive && (
        phase === 'editor-intro' ||
        phase === 'editor-content-inserted' ||
        phase === 'enhance-wait' ||
        phase === 'block-walkthrough' ||
        phase === 'publish-wait' ||
        phase === 'view-blog'
    );

    // ── Handle browser back button / Navigation Away ────────────────────────────
    // If the user navigates away using the browser back button or leaves the page, complete the tour.
    useEffect(() => {
        const handlePopState = () => {
            if (isActive) {
                apiUpdateProductTour().catch(e => console.error('Failed to complete tour on popstate:', e));
                completeOnboarding();
            }
        };

        window.addEventListener('popstate', handlePopState);
        return () => {
            window.removeEventListener('popstate', handlePopState);
            // Cleanup: if component unmounts while tour is active, complete it
            if (isActive) {
                apiUpdateProductTour().catch(e => console.error('Failed to complete tour on unmount:', e));
                completeOnboarding();
            }
        };
    }, [isActive, completeOnboarding]);

    // ── Phase: Editor Intro — wait for editor to mount ────────────────────────
    useEffect(() => {
        if (!isActive || phase !== 'editor-intro') return;
        if (setupRef.current['editor-intro']) return;
        setupRef.current['editor-intro'] = true;

        waitForElement(dataTourSelector('editor'), { timeout: 20000, interval: 200 })
            .then(el => { if (el) scrollToElement(el, { behavior: 'smooth', block: 'center' }); });
    }, [isActive, phase]);

    // ── "Load Demo Content" handler ───────────────────────────────────────────
    const handleInsertContent = useCallback(async () => {
        if (isInsertingContent) return;
        setIsInsertingContent(true);

        try {
            const content = demoContent?.content || sampleBlogData;

            // Push into store so PlateEditor re-renders
            handleBlogFieldChange('content', content as any);
            handleBlogFieldChange('blog_title', demoContent?.blog_title || 'Solar Panel Efficiency: Advanced Materials Driving Renewable Energy Innovation');

            // Notify PlateEditor to setValue() directly on the Plate instance
            window.dispatchEvent(
                new CustomEvent('onboarding:insert-content', { detail: { content } })
            );

            // Wait for content to render
            await new Promise<void>(r => setTimeout(r, 800));

            setPhase('editor-content-inserted');
        } finally {
            setIsInsertingContent(false);
        }
    }, [isInsertingContent, handleBlogFieldChange, setPhase, demoContent]);

    // ── Phase: editor-content-inserted → focus enhance button ─────────────────
    useEffect(() => {
        if (!isActive || phase !== 'editor-content-inserted') return;
        if (setupRef.current['content-inserted']) return;
        setupRef.current['content-inserted'] = true;

        let enhanceBtnEl: Element | null = null;

        const handleClick = () => {
            // When user clicks the real Enhance button, move to wait phase
            setPhase('enhance-wait');
        };

        waitForElement(dataTourSelector('enhance-btn'), { timeout: 8000, interval: 100 })
            .then(el => { 
                if (el) {
                    enhanceBtnEl = el;
                    el.addEventListener('click', handleClick);
                    scrollToElement(el, { behavior: 'smooth', block: 'nearest' }); 
                }
            });

        return () => {
            if (enhanceBtnEl) enhanceBtnEl.removeEventListener('click', handleClick);
        };
    }, [isActive, phase, setPhase]);

    // ── Phase: enhance-wait — listen for the real enhance API response ──────
    const handleEnhanceComplete = useCallback(async (event: Event) => {
        const data = (event as CustomEvent).detail;
        const content: any[] = data?.enhanced_content || [];

        if (!content.length) {
            // If somehow no content returned, skip to block-walkthrough with empty steps
            const steps: OnboardingBlockStep[] = BLOCK_SEQUENCE.map(b => ({ ...b, done: false }));
            setBlockSteps(steps);
            setPhase('block-walkthrough');
            return;
        }

        // 1. Auto-accept all AI-suggested blocks via API
        const pluginsToAccept = content.filter(block => block.is_ai_suggested);

        const acceptPromises = pluginsToAccept.map(block => {
            if (block.type === 'youtube_video') return Promise.resolve();

            const type = block.type as string;
            let idField = '';
            let suggestion_type = type;

            if (type === 'banner') {
                idField = 'banner_id';
            } else if (type === 'infograph') {
                idField = 'infograph_id';
                suggestion_type = 'info_graph';
            } else if (type === 'poll') {
                idField = 'poll_id';
            } else if (type === 'faq') {
                idField = 'faq_id';
            } else if (type === 'lead_magnet') {
                idField = 'lead_magnet_id';
            }

            if (idField && currentBlogId) {
                return aiSuggestionsApi.handleAcceptOrDeclineSuggestion({
                    blog_id: currentBlogId,
                    suggestion_type,
                    accept: true,
                    [idField]: block.plugin_data_id,
                }).catch(e => console.error('Onboarding auto-accept API failed:', e));
            }
            return Promise.resolve();
        });

        await Promise.all(acceptPromises);

        // Auto-convert banner component to image, upload it, and update the blog metadata featured_image
        const bannerBlock = pluginsToAccept.find(block => block.type === 'banner');
        if (bannerBlock && currentBlogId) {
            try {
                const banner = await bannersApi.handleGetBanner(bannerBlock.plugin_data_id);
                if (banner) {
                    const uploadedData = await handleConvertBannerComponentToImage(banner);
                    
                    let featuredImage: { url: string; image_id: string };
                    if (typeof uploadedData === 'string') {
                        featuredImage = {
                            url: uploadedData,
                            image_id: '',
                        };
                    } else if (uploadedData?.url) {
                        featuredImage = {
                            url: uploadedData.url,
                            image_id: uploadedData.image_id || uploadedData.id || '',
                        };
                    } else {
                        const url = uploadedData?.data?.url || uploadedData?.url || String(uploadedData);
                        featuredImage = {
                            url,
                            image_id: uploadedData?.data?.image_id || uploadedData?.image_id || uploadedData?.id || '',
                        };
                    }

                    const updatedBlog = await blogApi.handleUpdateBlog(currentBlogId, {
                        blog_info: {
                            ...(blog?.blog_info || {}),
                            featured_image: featuredImage,
                        },
                    });

                    if (updatedBlog) {
                        setBlog({
                            ...blog,
                            ...updatedBlog,
                            blog_info: {
                                ...(blog?.blog_info || {}),
                                ...(updatedBlog?.blog_info || {}),
                            },
                        });
                    }
                }
            } catch (error) {
                console.error('Error during onboarding banner conversion and upload:', error);
            }
        }

        // Small safety delay for DB
        await new Promise<void>(r => setTimeout(r, 500));

        // 2. Remove is_ai_suggested flag so blocks render as accepted
        const deeplyRemoveAiSuggested = (nodes: any[]): any[] =>
            nodes.map(node => {
                const newNode = { ...node };
                if ('is_ai_suggested' in newNode) delete newNode.is_ai_suggested;
                if (Array.isArray(newNode.children))
                    newNode.children = deeplyRemoveAiSuggested(newNode.children);
                return newNode;
            });

        const acceptedContent = deeplyRemoveAiSuggested(content);

        handleBlogFieldChange('content', acceptedContent as any);
        window.dispatchEvent(
            new CustomEvent('onboarding:insert-content', { detail: { content: acceptedContent } })
        );

        await new Promise<void>(r => setTimeout(r, 1000));

        // Wait for the first available AI block to confirm render
        const firstAiBlock = BLOCK_SEQUENCE.find(b =>
            content.some(c => c.type === b.type && c.is_ai_suggested !== undefined)
        );
        if (firstAiBlock) {
            await waitForElement(dataTourSelector(firstAiBlock.dataTour), {
                timeout: 15000,
                interval: 300,
            });
        }

        // 3. Build block steps in DOM order (top to bottom)
        const seenTypes = new Set<string>();
        const steps: OnboardingBlockStep[] = [];
        content.forEach((block: any) => {
            const matchedDef = BLOCK_SEQUENCE.find(b => b.type === block.type);
            if (matchedDef && !seenTypes.has(block.type)) {
                seenTypes.add(block.type);
                steps.push({ ...matchedDef, done: false });
            }
        });

        setBlockSteps(steps.length ? steps : BLOCK_SEQUENCE.map(b => ({ ...b, done: false })));
        setPhase('block-walkthrough');
    }, [handleBlogFieldChange, setBlockSteps, setPhase, currentBlogId]);

    useEffect(() => {
        if (!isActive || phase !== 'enhance-wait') return;

        window.addEventListener('onboarding:enhance-complete', handleEnhanceComplete);

        return () => {
            window.removeEventListener('onboarding:enhance-complete', handleEnhanceComplete);
        };
    }, [isActive, phase, handleEnhanceComplete]);


    // ── Phase: block-walkthrough — scroll to current block ───────────────────
    useEffect(() => {
        if (!isActive || phase !== 'block-walkthrough') return;
        if (!blockSteps.length) return;

        const currentStep = blockSteps[currentBlockIndex];
        if (!currentStep) {
            setPhase('publish-wait');
            return;
        }

        waitForElement(dataTourSelector(currentStep.dataTour), { timeout: 8000, interval: 200 })
            .then(el => { if (el) scrollToElement(el, { behavior: 'smooth', block: 'center' }); });

    }, [isActive, phase, currentBlockIndex, blockSteps, setPhase]);

    // ── Auto-advance: listen for accept/reject from any block ─────────────────
    // Block components fire `onboarding:block-action` when user accepts or rejects.
    useEffect(() => {
        if (!isActive || phase !== 'block-walkthrough') return;

        const handleBlockAction = () => {
            // Small delay so the UI settles before advancing
            setTimeout(() => advanceBlockStep(), 400);
        };

        window.addEventListener('onboarding:block-action', handleBlockAction);
        return () => window.removeEventListener('onboarding:block-action', handleBlockAction);
    }, [isActive, phase, advanceBlockStep]);

    // ── Phase: publish-wait — scroll to publish button ───────────────────────
    useEffect(() => {
        if (!isActive || phase !== 'publish-wait') return;
        if (setupRef.current['publish-wait']) return;
        setupRef.current['publish-wait'] = true;

        waitForElement(dataTourSelector('publish-btn'), { timeout: 8000, interval: 100 })
            .then(el => { if (el) scrollToElement(el, { behavior: 'smooth', block: 'nearest' }); });
    }, [isActive, phase]);

    // ── Phase: view-blog — scroll to view blog button ────────────────────────
    useEffect(() => {
        if (!isActive || phase !== 'view-blog') return;
        if (setupRef.current['view-blog']) return;
        setupRef.current['view-blog'] = true;

        waitForElement(dataTourSelector('view-blog-btn'), { timeout: 8000, interval: 100 })
            .then(el => { if (el) scrollToElement(el, { behavior: 'smooth', block: 'nearest' }); });
    }, [isActive, phase]);

    if (!isEditorPhase) return null;

    // ─────────────────────────────────────────────────────────────────────────
    // Render — no showSkip on any step from here on (step 2+)
    // ─────────────────────────────────────────────────────────────────────────

    // Step 2: Editor Intro
    if (phase === 'editor-intro') {
        return (
            <>
                <OnboardingSpotlight
                    active
                    targetSelector={null} // Full screen overlay
                    padding={0}
                />
                <OnboardingTooltip
                    active
                    targetSelector={null}
                    placement="auto"
                    content={{
                        title: 'Your AI Editor',
                        description: 'This is your powerful blog editor. We\'ll load a demo blog content so you can see all advanced features in action.',
                        icon: 'sparkles',
                        actionLabel: isInsertingContent ? 'Loading...' : 'Load Demo Content →',
                        onAction: handleInsertContent,
                        showSkip: true,
                        onSkip: completeOnboarding,
                    }}
                />
            </>
        );
    }

    // Step 3: Content Inserted — Show Enhance Button
    if (phase === 'editor-content-inserted') {
        return (
            <>
                <OnboardingSpotlight
                    active
                    targetSelector={dataTourSelector('enhance-btn')}
                    padding={10}
                />
                <OnboardingTooltip
                    active
                    targetSelector={dataTourSelector('enhance-btn')}
                    placement="auto"
                    content={{
                        title: 'Enhance Your Blog',
                        description: 'Hyperblog analyzes your post and creates everything around it.',
                        icon: 'zap',
                        showSkip: true,
                        onSkip: completeOnboarding,
                    }}
                />
            </>
        );
    }


    // Step 5: Block Walkthrough
    if (phase === 'block-walkthrough') {
        const currentStep = blockSteps[currentBlockIndex];
        if (!currentStep) return null;

        const isLastBlock = currentBlockIndex >= blockSteps.length - 1;
        const stepNumber = 5 + currentBlockIndex; // steps 5,6,7,8,9,10

        return (
            <>
                <OnboardingSpotlight
                    active
                    targetSelector={dataTourSelector(currentStep.dataTour)}
                    // Standard padding since the Accept/Reject bar is not shown
                    padding={12}
                />
                <OnboardingTooltip
                    active
                    targetSelector={dataTourSelector(currentStep.dataTour)}
                    placement="auto"
                    content={{
                        title: currentStep.label,
                        description: `${BLOCK_DESCRIPTIONS[currentStep.type] || 'An AI-generated block for your blog.'}`,
                        icon: 'sparkles',
                        // "Next Block" button as fallback if user wants to skip accepting/rejecting
                        actionLabel: isLastBlock ? 'Go to Publish →' : 'Next Block →',
                        onAction: advanceBlockStep,
                        showSkip: true,
                        onSkip: completeOnboarding,
                    }}
                />
            </>
        );
    }

    // Publish step
    if (phase === 'publish-wait') {
        return (
            <>
                <OnboardingSpotlight
                    active
                    targetSelector={dataTourSelector('publish-btn')}
                    padding={12}
                />
                <OnboardingTooltip
                    active
                    targetSelector={dataTourSelector('publish-btn')}
                    placement="auto"
                    content={{
                        title: 'Publish Your Blog',
                        description: 'Your sample blog is ready to publish. You can delete later',
                        icon: 'zap',
                        showSkip: true,
                        onSkip: completeOnboarding,
                    }}
                />
            </>
        );
    }

    // View Blog (final step — shown after successful publish)
    if (phase === 'view-blog') {
        return (
            <>
                <OnboardingSpotlight
                    active
                    targetSelector={dataTourSelector('view-blog-btn')}
                    padding={12}
                />
                <OnboardingTooltip
                    active
                    targetSelector={dataTourSelector('view-blog-btn')}
                    placement="auto"
                    content={{
                        title: 'View Published Blog 🎉',
                        description: 'Open your published blog in a new tab. You\'re all set!',
                        icon: 'sparkles',
                        actionLabel: 'Finish Tour ✓',
                        onAction: completeOnboarding,
                        showSkip: true,
                        onSkip: completeOnboarding,
                    }}
                />
            </>
        );
    }

    return null;
}
